services:
  server:
    build: ./server
    working_dir: /app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 4000
    ports:
      - "4000:4000"

  ui:
    build: ./ui
    ports:
      - "3000:80"
    depends_on:
      - server
