name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install & build server
        working-directory: ./server
        run: |
          npm install
          npm run build || true
      - name: Install & build ui
        working-directory: ./ui
        run: |
          npm install
          npm run build
